# Generated by Django 2.2.16 on 2022-05-22 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220519_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка 1-10!'), django.core.validators.MaxValueValidator(10, message='Оценка 1-10!')]),
        ),
    ]
